######################################################################
# Automatically generated by qmake (3.0) ?? 3? 4 17:28:02 2015
######################################################################

TEMPLATE = app
TARGET = goBang
INCLUDEPATH += .

# Input
HEADERS += chess.h goBang.h
SOURCES += chess.cpp goBang.cpp main.cpp
QT += widgets
